repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        language_version: python3
        stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        language_version: python3
        args: [--max-line-length=88]
        stages: [commit]
default_language_version:
    python: python3.6, python3.7
default_stages: [commit]

